server:
  port: 8086

spring:
  application:
    name: common-master-service

  datasource:
    url: jdbc:mysql://localhost:3306/school_erp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_schema: public
    defer-datasource-initialization: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  config:
    import: "optional:configserver:"

#  cloud:
#    config:
#      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
#      fail-fast: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.schoolerp.student: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{logId:-}] [%X{requestId:-}] [%X{operation:-}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{logId:-}] [%X{requestId:-}] [%X{operation:-}] [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/student-service.log

# Custom application properties
app:
  name: Common Master Service
  version: 1.0.0
  description: Microservice for managing common master data in the School ERP system

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka server URL
  instance:
    prefer-ip-address: true

  eureka:
    instance:
      hostname: localhost
      prefer-ip-address: true
